Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204" # https://app.vagrantup.com
  config.vm.box_version = "4.2.6" # >= 4.2.6
  config.vm.hostname = "virtualbox-guest-vm" # Vagrant will update /etc/hosts on the guest with the configured hostname.
  config.vm.network "private_network", ip: "192.168.10.55"   # Configures networks on the machine.

  config.vm.provider "virtualbox" do |vb|
    vb.name = "may-ao-01"
    vb.cpus = 2
    vb.memory = 2048
  end

  config.vm.provision "shell" do |s|
  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
  s.inline = <<-SHELL
    # Create ci user
    useradd -s /bin/bash -d /home/ci/ -m -G sudo ci
    echo 'ci ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
    mkdir -p /home/ci/.ssh && chown -R ci /home/ci/.ssh
    echo #{ssh_pub_key} >> /home/ci/.ssh/authorized_keys
  SHELL
  end
end
