#https://docs.gitlab.com/ee/ci/

variables:
  IMAGE_NAME: kukun/rust-users-gitlab
  IMAGE_TAG: latest
stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: rust:latest
  before_script:
    - apt-get update
    - apt-get install -y libpq-dev clang
  script:
    - cargo test

#https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#option-1-run-docker-login
build_image:
  stage: build
  image: docker:23.0.1 # https://hub.docker.com/_/docker/
  services:
    - docker:23.0.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS
    - docker info
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -f ./users/docker/production/Dockerfile .
    - docker push $IMAGE_NAME:$IMAGE_TAG


#deploy:
#  stage: deploy
#  before_script:
#    - chmod 400 $SSH_KEY
#  script:
#    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@161.35.223.117 "
#      docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS &&
#      docker ps -aq | xargs docker stop | xargs docker rm &&
#      docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"