version: '3.9'
services:
  # Satellites service
  actix:
    build:
      context: .
      dockerfile: ./actix/Dockerfile
    container_name: actix-service
    restart: always
    depends_on:
      - actix-db
    environment:
      DATABASE_URL: postgres://postgres:$ACTIX_DB_PASSWORD@actix-db/actix
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:7002/" ]
      interval: 1m
      timeout: 3s
      start_period: 10s
      retries: 3
    ports:
      - "7002:7001"
  actix-db:
    image: postgres:15.0-alpine
    container_name: actix-db
    restart: always
    environment:
      POSTGRES_DB: actix
      POSTGRES_PASSWORD: $ACTIX_DB_PASSWORD
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1m
      timeout: 5s
      start_period: 10s
      retries: 3
