version: '3.9'
services:
  # Users service
  users:
    build:
      context: .
      dockerfile: ./microservice/users/Dockerfile
    container_name: users
    restart: always
    depends_on:
      - user-db-host
    environment:
      DATABASE_URL: postgres://postgres:$USERS_DB_PASSWORD@user-db-host/users
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:1405/" ]
      interval: 1m
      timeout: 3s
      start_period: 10s
      retries: 3
    ports:
      - "1405:80"
  user-db-host:
    image: postgres:15.1-alpine
    container_name: user-db-host
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_PASSWORD: $USERS_DB_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1m
      timeout: 5s
      start_period: 10s
      retries: 3
