version: '3.9'
services:
  # Users service
  users:
    build:
      context: ./
      dockerfile: ./users/docker/dev.Dockerfile
    container_name: users
    restart: always
    depends_on:
      - user-db-host
    environment:
      DATABASE_URL: postgres://postgres:$USERS_DB_PASSWORD@user-db-host/users
      PASSWORD_SECRET_KEY: $PASSWORD_SECRET_KEY
      JWT_SECRET_KEY: $JWT_SECRET_KEY
    volumes:
      - ./users:/usr/src/users
      - ./common-utils:/usr/src/common-utils
    command: bash -c "cargo run"
    ports:
      - "1405:80"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost/" ]
      interval: 1m
      timeout: 3s
      start_period: 10s
      retries: 3
  # Users database service
  user-db-host:
    image: postgres:15.1-alpine
    container_name: user-db-host
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_PASSWORD: $USERS_DB_PASSWORD
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1m
      timeout: 5s
      start_period: 10s
      retries: 3
