[default]
address = "127.0.0.1" # IP address to serve on
cli_colors = true #Whether to use colors and emoji when logging.
extra = false
ident = "Rocket Server" # If and how to identify via the Server header.
keep_alive = 5 # Keep-alive timeout seconds; disabled when 0.
log_level = "critical" # Max level to log. (off/normal/debug/critical)
limits = { json = "1MiB", forms = "64 kB", msgpack = "2MiB", "file/jpg" = "5 MiB" } # Streaming read size limits.
log_level = "critical" # Max level to log. (off/normal/debug/critical)
max_blocking = 512 # Limit on threads to start for blocking tasks.

workers = 16 # Number of threads to use for executing futures. (cpu core count)

[debug]
keep_alive = 0
ident = "Rocket Dev" # If and how to identify via the Server header.
limits = { json = "10MiB" }
log_level = "normal"
port = 8000

[nyc]
port = 8000

[release]
ident = "Rocket 1" # If and how to identify via the Server header.
keep_alive = 5
log_level = "critical"
port = 8000
secret_key = "fmGv6wauRz/i0zpmMh4l8gukCEhROM+u7QGFiI3qetU=" #openssl rand -base64 32

