Vagrant.configure("2") do |config|

    # Machines 1
    config.vm.define "virtualbox-guest-vm-1" do |os1|
        os1.vm.box = "generic/ubuntu2204" # https://app.vagrantup.com
        os1.vm.box_version = "4.2.6" # >= 4.2.6
        os1.vm.hostname = "virtualbox-guest-vm-1"
        os1.vm.network "private_network", ip: "172.16.16.11"
        os1.vm.provider "virtualbox" do |vb|
            vb.name = "virtualbox-guest-vm-1"
            vb.memory = 2048
            vb.cpus = 2
        end
    end

    # Machines 2
    config.vm.define "virtualbox-guest-vm-2" do |os2|
        os2.vm.box = "generic/ubuntu2204" # https://app.vagrantup.com
        os2.vm.box_version = "4.2.6" # >= 4.2.6
        os2.vm.hostname = "virtualbox-guest-vm-2"
        os2.vm.network "private_network", ip: "172.16.16.12"
        os2.vm.provider "virtualbox" do |vb|
            vb.name = "virtualbox-guest-vm-2"
            vb.memory = 2048
            vb.cpus = 2
        end
    end

    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
        # Create ci user
        useradd -s /bin/bash -d /home/ci/ -m -G sudo ci
        echo 'ci ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
        mkdir -p /home/ci/.ssh && chown -R ci /home/ci/.ssh
        echo #{ssh_pub_key} >> /home/ci/.ssh/authorized_keys
        SHELL
    end
end
