name: CI/CD Service Users

on:
  push:
    branches: [ "services/users" ]
  pull_request:
    branches: [ "services/users" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-services:
    runs-on: ubuntu-latest
    steps:
      # uses: actions/checkout@v3 trong tệp .github/workflows/ là một dòng cấu hình cho GitHub Actions.
      # Nó chỉ định sử dụng action checkout từ tập tin actions/checkout với phiên bản v3.
      # Action checkout cho phép bạn clone tệp của dự án từ kho lưu trữ GitHub vào môi trường runner của GitHub Actions để thực hiện các bước khác trong workflow.
      # Điều này cho phép bạn truy cập vào mã nguồn của dự án để thực hiện các tác vụ như biên dịch, kiểm tra, v.v.
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installs Rust toolchain
        uses: actions-rs/toolchain@v1 # https://github.com/actions-rs/toolchain
        with:
          toolchain: stable
          override: true

      - name: Runs specified cargo command Test
        uses: actions-rs/cargo@v1 # https://github.com/actions-rs/cargo
        with:
          command: test